// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pessimisticvalidation/lightclient/v1/clientmsg.proto

package lightclient

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v8/modules/core/02-client/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PessimisticClaims is the clientMsg that is sent to the light client to update
// the consensus state
// TODO: Document more
type PessimisticClaims struct {
	Claims []PacketCommitmentsClaim `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims"`
}

func (m *PessimisticClaims) Reset()         { *m = PessimisticClaims{} }
func (m *PessimisticClaims) String() string { return proto.CompactTextString(m) }
func (*PessimisticClaims) ProtoMessage()    {}
func (*PessimisticClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad4b3d4b72c7f07d, []int{0}
}
func (m *PessimisticClaims) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PessimisticClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PessimisticClaims.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PessimisticClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PessimisticClaims.Merge(m, src)
}
func (m *PessimisticClaims) XXX_Size() int {
	return m.Size()
}
func (m *PessimisticClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_PessimisticClaims.DiscardUnknown(m)
}

var xxx_messageInfo_PessimisticClaims proto.InternalMessageInfo

func (m *PessimisticClaims) GetClaims() []PacketCommitmentsClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

// TODO: Document more
// TODO: Check if we need more information in the claim like height, app hash,
// etc
type PacketCommitmentsClaim struct {
	ValidatorAddress  []byte       `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	PacketCommitments [][]byte     `protobuf:"bytes,2,rep,name=packet_commitments,json=packetCommitments,proto3" json:"packet_commitments,omitempty"`
	Signature         []byte       `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Height            types.Height `protobuf:"bytes,4,opt,name=height,proto3" json:"height"`
}

func (m *PacketCommitmentsClaim) Reset()         { *m = PacketCommitmentsClaim{} }
func (m *PacketCommitmentsClaim) String() string { return proto.CompactTextString(m) }
func (*PacketCommitmentsClaim) ProtoMessage()    {}
func (*PacketCommitmentsClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad4b3d4b72c7f07d, []int{1}
}
func (m *PacketCommitmentsClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PacketCommitmentsClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PacketCommitmentsClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PacketCommitmentsClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketCommitmentsClaim.Merge(m, src)
}
func (m *PacketCommitmentsClaim) XXX_Size() int {
	return m.Size()
}
func (m *PacketCommitmentsClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketCommitmentsClaim.DiscardUnknown(m)
}

var xxx_messageInfo_PacketCommitmentsClaim proto.InternalMessageInfo

func (m *PacketCommitmentsClaim) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *PacketCommitmentsClaim) GetPacketCommitments() [][]byte {
	if m != nil {
		return m.PacketCommitments
	}
	return nil
}

func (m *PacketCommitmentsClaim) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PacketCommitmentsClaim) GetHeight() types.Height {
	if m != nil {
		return m.Height
	}
	return types.Height{}
}

func init() {
	proto.RegisterType((*PessimisticClaims)(nil), "pessimisticvalidation.lightclient.v1.PessimisticClaims")
	proto.RegisterType((*PacketCommitmentsClaim)(nil), "pessimisticvalidation.lightclient.v1.PacketCommitmentsClaim")
}

func init() {
	proto.RegisterFile("pessimisticvalidation/lightclient/v1/clientmsg.proto", fileDescriptor_ad4b3d4b72c7f07d)
}

var fileDescriptor_ad4b3d4b72c7f07d = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x6e, 0xea, 0x30,
	0x14, 0x86, 0x93, 0x0b, 0x42, 0xba, 0x86, 0xe1, 0x62, 0x5d, 0x5d, 0x45, 0xe8, 0x2a, 0x20, 0xd4,
	0x21, 0x52, 0x85, 0x2d, 0x68, 0x87, 0x0e, 0x2c, 0x85, 0xa5, 0x23, 0x62, 0xe8, 0xc0, 0x82, 0x1c,
	0xc7, 0x32, 0x6e, 0xe3, 0x38, 0xb2, 0x0d, 0xcf, 0xd1, 0xc7, 0x62, 0xe8, 0xc0, 0xd8, 0xa9, 0xaa,
	0xe0, 0x45, 0xaa, 0x38, 0xb4, 0x41, 0x88, 0xa1, 0xdb, 0xd1, 0xf1, 0xff, 0x7f, 0x3e, 0xff, 0xb1,
	0xc1, 0x6d, 0xce, 0x8c, 0x11, 0x52, 0x18, 0x2b, 0xe8, 0x86, 0xa4, 0x22, 0x21, 0x56, 0xa8, 0x0c,
	0xa7, 0x82, 0xaf, 0x2c, 0x4d, 0x05, 0xcb, 0x2c, 0xde, 0x0c, 0x71, 0x59, 0x49, 0xc3, 0x51, 0xae,
	0x95, 0x55, 0xf0, 0xea, 0xa2, 0x0b, 0x9d, 0xb8, 0xd0, 0x66, 0xd8, 0xf9, 0xcb, 0x15, 0x57, 0xce,
	0x80, 0x8b, 0xaa, 0xf4, 0x76, 0xba, 0x22, 0xa6, 0x98, 0x2a, 0xcd, 0xf0, 0x39, 0xbf, 0x14, 0xf4,
	0x15, 0x68, 0xcf, 0x2a, 0xfc, 0x34, 0x25, 0x42, 0x1a, 0xb8, 0x00, 0x0d, 0xea, 0xaa, 0xc0, 0xef,
	0xd5, 0xa2, 0xe6, 0x68, 0x8c, 0x7e, 0x32, 0x02, 0x9a, 0x11, 0xfa, 0xcc, 0xec, 0x54, 0x49, 0x29,
	0xac, 0x64, 0x99, 0x35, 0x0e, 0x37, 0xa9, 0x6f, 0xdf, 0xbb, 0xde, 0xfc, 0x48, 0xec, 0xbf, 0xfa,
	0xe0, 0xdf, 0x65, 0x21, 0xbc, 0x06, 0xed, 0x23, 0x5c, 0xe9, 0x25, 0x49, 0x12, 0xcd, 0x4c, 0x31,
	0x81, 0x1f, 0xb5, 0xe6, 0x7f, 0xbe, 0x0f, 0xee, 0xcb, 0x3e, 0x1c, 0x00, 0x98, 0x3b, 0xcc, 0x92,
	0x56, 0x9c, 0xe0, 0x57, 0xaf, 0x16, 0xb5, 0xe6, 0xed, 0xfc, 0xfc, 0x02, 0xf8, 0x1f, 0xfc, 0x36,
	0x82, 0x67, 0xc4, 0xae, 0x35, 0x0b, 0x6a, 0x8e, 0x59, 0x35, 0xe0, 0x1d, 0x68, 0xac, 0x58, 0x11,
	0x26, 0xa8, 0xf7, 0xfc, 0xa8, 0x39, 0xea, 0x20, 0x11, 0x53, 0x54, 0xec, 0x0d, 0x55, 0xf1, 0x1e,
	0x9c, 0xe2, 0x2b, 0x4e, 0xa9, 0x9f, 0x3c, 0x6e, 0xf7, 0xa1, 0xbf, 0xdb, 0x87, 0xfe, 0xc7, 0x3e,
	0xf4, 0x5f, 0x0e, 0xa1, 0xb7, 0x3b, 0x84, 0xde, 0xdb, 0x21, 0xf4, 0x16, 0x63, 0x2e, 0xec, 0x6a,
	0x1d, 0x23, 0xaa, 0x24, 0xe6, 0x4f, 0x4c, 0xcb, 0x75, 0x96, 0x70, 0xa2, 0x49, 0x4c, 0xf0, 0xc9,
	0x36, 0x07, 0x97, 0xff, 0x41, 0xdc, 0x70, 0xcf, 0x73, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xdb, 0x93, 0xa5, 0x33, 0x02, 0x00, 0x00,
}

func (m *PessimisticClaims) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PessimisticClaims) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PessimisticClaims) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClientmsg(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PacketCommitmentsClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PacketCommitmentsClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PacketCommitmentsClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Height.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClientmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintClientmsg(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PacketCommitments) > 0 {
		for iNdEx := len(m.PacketCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PacketCommitments[iNdEx])
			copy(dAtA[i:], m.PacketCommitments[iNdEx])
			i = encodeVarintClientmsg(dAtA, i, uint64(len(m.PacketCommitments[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintClientmsg(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintClientmsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovClientmsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PessimisticClaims) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovClientmsg(uint64(l))
		}
	}
	return n
}

func (m *PacketCommitmentsClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovClientmsg(uint64(l))
	}
	if len(m.PacketCommitments) > 0 {
		for _, b := range m.PacketCommitments {
			l = len(b)
			n += 1 + l + sovClientmsg(uint64(l))
		}
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovClientmsg(uint64(l))
	}
	l = m.Height.Size()
	n += 1 + l + sovClientmsg(uint64(l))
	return n
}

func sovClientmsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClientmsg(x uint64) (n int) {
	return sovClientmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PessimisticClaims) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PessimisticClaims: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PessimisticClaims: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClientmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClientmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, PacketCommitmentsClaim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClientmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PacketCommitmentsClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PacketCommitmentsClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PacketCommitmentsClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = append(m.ValidatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorAddress == nil {
				m.ValidatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketCommitments = append(m.PacketCommitments, make([]byte, postIndex-iNdEx))
			copy(m.PacketCommitments[len(m.PacketCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClientmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClientmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClientmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClientmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClientmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClientmsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClientmsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClientmsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClientmsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClientmsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClientmsg = fmt.Errorf("proto: unexpected end of group")
)
