[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[tracing_server]
enabled = false
port = 5555

[[chains]]
type = "CosmosSdk"
id = "simapp-1"
rpc_addr = "http://0.0.0.0:26657"
grpc_addr = "tcp://0.0.0.0:8090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "simapp"
key_name = "relayer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = "gg tech"
sequential_batch_tx = false
gas_price = { price = 0.025, denom = 'stake' }
address_type = { derivation = 'cosmos' }
event_source = { mode = 'pull', interval = '500ms', max_retries = 4 }

[[chains]]
type = "CosmosSdk"
id = "rollupsimapp-1"
rpc_addr = "http://0.0.0.0:36657"
grpc_addr = "tcp://0.0.0.0:9091"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "rollup"
key_name = "relayer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = "gg tech"
sequential_batch_tx = false
gas_price = { price = 0.025, denom = 'stake' }
address_type = { derivation = 'cosmos' }
event_source = { mode = 'pull', interval = '500ms', max_retries = 4 }

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "stake"

[chains.packet_filter]
policy = "allowall"

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = true
multiplier = 1.5
max = 0.6
