name: pessimistic-validation-demo

services:
  #mock-da:
  #  container_name: mock-da
  #  hostname: mock-da
  #  image: mock-da:local
  #  ports:
  #    - 7980:7980
  #  entrypoint:
  #    - /usr/bin/mock-da
  local-celestia-devnet:
    container_name: local-celestia-devnet
    hostname: local-celestia-devnet
    image: ghcr.io/gjermundgaraba/local-celestia-devnet:shared-auth-token
    ports:
      - 26650
      - 26657
      - 26658
      - 26659
      - 9090
    entrypoint:
      - /bin/bash
      - /opt/entrypoint.sh
    volumes:
      - shared-data:/home/celestia/shared-data
    environment:
      - CELESTIA_NAMESPACE=00000000000000000000000000000000000000000008e5f679bf7116cb
  hub:
    container_name: hub
    hostname: hub
    image: hub:local
    init: true
    entrypoint: #TODO: Make it into a loop that tries to start the validator?
      - ignite
      - chain
      - serve
      - --verbose
    ports:
      - 26656
      - 26657:26657
      - 1317
    environment:
      - PESSIMIST_CONFIG_PATH=/root/pessimist.yaml
  rolly:
    container_name: rolly
    hostname: rolly
    image: rolly:local
    init: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10
        /code/init.sh celestia http://local-celestia-devnet:26658 http://local-celestia-devnet:26657
    ports:
      - 27657:27657
    depends_on:
      - local-celestia-devnet
    volumes:
      - shared-data:/root/shared-data
volumes:
  shared-data: