global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
  log-level: info
  ics20-memo-limit: 0
  max-receiver-size: 150
chains:
  hub:
    type: cosmos
    value:
      key: default
      chain-id: hub
      rpc-addr: tcp://127.0.0.1:26657
      account-prefix: hub
      keyring-backend: test
      gas-adjustment: 2.5
      gas-prices: 0.05stake
      min-gas-amount: 0
      max-gas-amount: 0
      debug: true
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: null
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []
      feegrants: null
  rolly:
    type: cosmos
    value:
      key: default
      chain-id: rolly
      rpc-addr: tcp://127.0.0.1:27657
      account-prefix: rolly
      keyring-backend: test
      gas-adjustment: 2.5
      gas-prices: 0.05stake
      min-gas-amount: 0
      max-gas-amount: 0
      debug: true
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: null
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []
      feegrants: null
paths:
  regular-path:
    src:
      chain-id: hub
    dst:
      chain-id: rolly
    src-channel-filter:
      rule: ""
      channel-list: []
  pessimist-path:
    src:
      chain-id: rolly
      client-id: 07-tendermint-0
    dst:
      chain-id: hub
      client-id: 69-pessimist-1
    src-channel-filter:
      rule: ""
      channel-list: []