name: "Unit testing"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            core/go.sum
            configmodule/go.sum
            sidecar/go.sum
            testing/interchaintest/go.sum
            testing/simapp/go.sum
            testing/rollupsimapp/go.sum
      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run tests
        run: just test-unit

